### ISSUE TITLE
Cannot post a message

### ISSUE THREAD

**Issue by anxolerd** [notwaldorf/mojibrag#14]
## Description
I cannot post a message, moreover I have really little controlls working.

## Screenshot
On the screenshot you can see, that cursor over post button is normal, while it is supposed to be point (hand)
![image](https://cloud.githubusercontent.com/assets/6533582/19363955/cf24f788-9194-11e6-8fce-5b3846450bdb.png)

## Investigation
Browser: Google Chrome Version 53.0.2785.143 (64-bit)
OS: Linux (Fedora 24)

Openinig Chrome DevTools showed me the following:
![image](https://cloud.githubusercontent.com/assets/6533582/19364038/391055ac-9195-11e6-85d1-be4e57042bf7.png)
Please, note the hovered element is posts list, not the new-post card.

If I delete that element from DOM (via DevTools) I'll be able to create a post
![image](https://cloud.githubusercontent.com/assets/6533582/19364102/811f0b5e-9195-11e6-9378-9d308563fb31.png)

**Comment by notwaldorf** [comment]
Thanks for trying it out! 

Yeah, there's totally something going funky here. Basically the `iron-list` sits on top of everything, but it has `position-static` so it shouldn't create a static context.

Unfortunately I can't repro this (my Chrome works fine, which is a bit bananas), and @blasten, who is the owner of `iron-list` is on a plane so he can't take a look, but we'll try to fix it this weekend.

In the meantime, I think you can tab through all the things but that's a bit annoying. Sorry for the inconvenience 😓

**Comment by anxolerd** [comment]
Well, nothing to sorry about =)
If you need any info to investigate this, I'll be glad to provide it.

**Comment by notwaldorf** [comment]
The problem is that the `iron-list` needs to have that weird negative margin/padding hack (because otherwise clicking on it is a bit messed up), so we can't get rid of that. `position:static` shooooould have fixed it buuuut *shrug*

**Comment by anxolerd** [comment]
Huh, I've just figured that out by finding and disabling them =|

**Comment by anxolerd** [comment]
Hm, by the way, everything works fine on 
Google Chrome Version 55.0.2883.9 dev (64-bit)

**Comment by jonuy** [comment]
For what it's worth, I got it to work for me by removing the `postition: static` and adding a `z-index: -1` on the `#list` while in dev tools. ¯\_(ツ)_/¯

**Comment by notwaldorf** [comment]
@jonuy If you do that, then you won't be able to interact with the posts -- I.e liking them or pressing the delete/hint buttons.
