### ISSUE TITLE
<channel-item> and <view-posts> overflow if you feed the channel name with too much tildes

### ISSUE THREAD

**Issue by wongmjane** [notwaldorf/mojibrag#35]
![screenshot](https://cloud.githubusercontent.com/assets/1332975/19539718/ee7e0456-9628-11e6-8178-08005a480bbb.png)

**Comment by anxolerd** [comment]
What do you mean by 
> feed the channel name with too much tildes
?

**Comment by wongmjane** [comment]
> What do you by saying

>> feed the channel name with too much tildes

> ?

Re @anxolerd: Essentially if the channel name contains no breakable words and is too long, the `<channel-item>` will overflow as shown in the picture above.

**Comment by wongmjane** [comment]
If the channel name is an unbreakable word that's too long, it will overflow

On Oct 22, 2016 18:08, "Oleksandr" <notifications@github.com> wrote:

What do you mean by

feed the channel name with too much tildes
?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/notwaldorf/mojibrag/issues/35#issuecomment-255556938>,
or mute the thread

**Comment by anxolerd** [comment]
@wongmjane: thanks
